dbt_athena_iceberg_datalake:
  outputs:
    dev:
      database: awsdatacatalog
      region_name: eu-west-1
      s3_data_dir: s3://dbt-tables-sandbox/dbt-athena-iceberg-datalake
      s3_staging_dir: s3://dbt-query-dump-sandbox/dbt-athena-iceberg-datalake
      schema: dbt-athena-iceberg-datalake
      threads: 4
      type: athena
  target: dev